### ISSUE TITLE
The enabled pubpeer plug-in affects the display of other plug-in settings.

### ISSUE THREAD

**Issue by tcmtom** [PubPeerFoundation/pubpeer_zotero_plugin#44]
When the pubpeer plug-in is enabled, the setting items of these two plug-ins are not displayed in the setting box.
This is the feedback under two plug-ins (Chinese)：
https://github.com/windingwind/zotero-pdf-translate/issues/393
https://github.com/MuiseDestiny/zotero-reference/issues/90

**Comment by retorquere** [comment]
Are you sure that it's pubpeer specifically? Pubpeer doesn't touch the prefs pane.

**Comment by retorquere** [comment]
Can you:

* install build 43 just posted above
* go into Help - Debug output logging - restart
* Go Help - Send debug log to file.io

You will get a popup with an alphanumeric string, please post that here.

**Comment by retorquere** [comment]
That is a zotero debug log. Please use the "send to file.io" option.

**Comment by retorquere** [comment]
No errors in that log. Any one of zotero-pdf-translate and zotero-reference exhibits the problem?

**Comment by retorquere** [comment]
I can't read Chinese, so I can't tell. It seems to be because we use the DOM parser, if I comment that out, the prefs screen of the other plugin loads without issue.

The problem apparently is that Zotero has two XML DOM parsers built in; pubpeer uses nsiDOMParser, and it looks like pdf translate uses the other under some circumstances, and apparently that doesn't work. But it isn't immediately clear to me who should move here. Using nsiDOMParser is a valid approach, and while we could switch to the other domparser, that might mean pubpeer would break if someone else uses nsiDOMParser.

@windingwind, what is your take on this?

**Comment by windingwind** [comment]
I am also very confused with the DOMParser issue. I tended to report and discuss this in the dev group several days ago, while my mail address is banned in the dev group. According to the Zotero team, it is because Google recognizes me as an ad robot (which is apparently not) and this happens to some other users as well.

From my practice, the two DOMParser seem to have different behaviors and different compatibilities. Not sure which one we should use, but Zotero uses them both in their code. I also know there are some other related issues like the RSS doesn't work bug.

By any means, I guess this might be a bug with the Zotero side, as some failure with calling DOMParser should never cause the DOMParser itself unusable. Could you please report this to the dev group? I'm still waiting for Google to unblock me.

**Comment by retorquere** [comment]
> while my mail address is banned in the dev group

that's stupid

> Could you please report this to the dev group?

They'll want a reproducible minimal implementation -- I'm sorry, but I can't commit to that right now given my schedule. I'm using `@xmldom` anyhow for #38, I'll just see whether that can also be used for #44. It bloats the plugin a bit, but it is the path of least resistance towards a working situation.

**Comment by windingwind** [comment]
Hopefully, these annoying things will be gone in Zotero 7, which runs on FF 102 with a standard built-in DOMParser. I cannot wait to say goodbye to the nsiXXX things.

**Comment by retorquere** [comment]
I still have a looooong way to go before BBT is ready for 7. I finally have a prefs screen that I can load dynamically, which was the first step.

**Comment by windingwind** [comment]
Me tooooo. I am currently doing a total refactoring for the better notes plugin for Z7. Painful!

**Comment by retorquere** [comment]
I had already switched to xmldom for #38, so I've just issued a new release that bundles that change. Please upgrade to 0.0.16, that should resolve the issue.

**Comment by retorquere** [comment]
Why would you want it removed?
